# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  pull_request:
    branches: [dev_gaurav]
  push:
    branches: [ dev_gaurav ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
     
     - name: Checkout Repo
       uses: actions/checkout@master
     - name: Removing package-lock file
       run: rm -rf package-lock.json
     - name: Install Dependencies
       run: sudo npm install
     - name: Build Prod
       run: sudo npm build --prod
     - name: Archive Production Artifact
       uses: actions/upload-artifact@master
       with:
          name: portfolio-gaurav
          path: dist/portfolio-gaurav
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: portfolio-gaurav
          path: dist/portfolio-gaurav
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
       
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
             
   
