# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ dev_gaurav ]

jobs:
  firebase-deploy:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    
    steps: 
      - uses: actions/checkout@v1
            run:|
              npm install
              npm run build --prod
            run:|
              sudo npm install -g firebase-tools
              firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
   
